[package]
name = "tagmv"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
lofty = "0.22"
clap = { version = "4", features = ["derive"] }
colored = "3"
walkdir = "2"
anyhow = "1"
libc = "0.2"
